// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fghuooonabkftyuzjtlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnaHVvb29uYWJrZnR5dXpqdGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNjkzNTYsImV4cCI6MjA2MTc0NTM1Nn0.leQjB18q5Ujmgm3-dAJJsm-tZXnOs52Ey879qVvPosc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);