// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehrkwpalhodpntntiyyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVocmt3cGFsaG9kcG50bnRpeXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODEzMTMsImV4cCI6MjA3MjM1NzMxM30.nEmFwDwI16nHAa874uuG-5qCqNlIUzn33_AvbAMPJGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});